### ISSUE TITLE
Feature request: Use something like Code Mirror for syntax highlighting and indentation

### ISSUE THREAD

**Issue by mhavard999** [mathiasbynens/jsperf.com#228] opened 2015-05-07 13:56 UTC
It would be nice if the text inputs had syntax highlighting and auto indentation.  [Code Mirror](http://codemirror.com/) is a popular library for syntax highlighting in the browser.

**Comment by mathiasbynens** [comment] 2015-05-07 14:39
Duplicate of #227.

**Closed as completed by mathiasbynens** 2015-05-07 14:39 UTC
Labels: duplicate
