### ISSUE TITLE
Comparison of performance is incorrect when differing by more than a factor of 10.

### ISSUE THREAD

**Issue by reichstein** [mathiasbynens/jsperf.com#12] opened 2011-07-12 07:37 UTC

**Comment by mathiasbynens** [comment] 2011-07-12 07:47
What do you mean exactly? Can you give an example?

**Comment by reichstein** [comment] 2011-07-12 07:51
Sorry, early commit.
See http://jsperf.com/test-jsperf-comparison
It claims performances of 0.2 ops/sec and 2.0 ops per sec are equal and better than 10 ops/sec.
Seems speeds are compared textually?

**Comment by jdalton** [comment] 2011-07-12 14:04
@reichstein Thanks for the report, the wiggle room we give the comparison formula falls apart on the lower ops/sec values and needs to be adjusted. I will try to smooth this out asap. Thanks.

**Comment by jdalton** [comment] 2011-07-12 14:32
@reichstein I found the issue, it's a math error caused by dividing by zero creating an `NaN` value for the `bench.stats.moe` value which is happening on the reaaaaallly slow tests.

**Comment by mathiasbynens** [comment] 2011-07-14 05:47
Fixed in this commit: https://github.com/bestiejs/benchmark.js/commit/2dc303c9edb2a45c9e288538273df87bb4e5bca6

**Closed as completed by mathiasbynens** 2011-07-14 05:47 UTC
